### ISSUE TITLE
Drop `provider_locations.eligibility` field

### ISSUE THREAD

**Issue by Mr0grog** [usdigitalresponse/univaf#154]
Our provider locations currently have a field named `eligibility` that we don’t use. We originally thought we’d be able to gather eligibility requirements, like minimum age, whether only same-county residents are allowed, etc. in a structured way, but that hasn’t really borne out, and where we have this kind of info, it’s part of the `description`.

We should drop the `eligibility` field on locations.

This will need:
- Migration to remove the field from the `provider_locations` table in the database.
- Probably some updates to code `server/src/db.ts` to remove references to that field.

**Comment by channiemills** [comment]
Closed by #279 - please let me know if there are any questions or concerns.
