### ISSUE TITLE
Add ability to disable loaders

### ISSUE THREAD

**Issue by astonm** [usdigitalresponse/univaf#218]
During data migrations and other planned API outages, the large number of requests the loaders send to the server can be a nuisance. Currently we can somewhat hackily disable loaders by changing their scheduled run rate to something rare (e.g. `rate(1 day)`) but it would be nice to be able to disable them in a more straightforward way.

**Comment by Mr0grog** [comment]
Note: this functionality is built-in on Render (although you have to do it through the web console instead of `render.yaml`), so #683 results in us switching platforms, this issue will be solved.
