### ISSUE TITLE
Validate that external ID systems do not have colons

### ISSUE THREAD

**Issue by Mr0grog** [usdigitalresponse/univaf#223]
The question: “are we sure that no external ID systems have `:` in their name?” keeps coming up in various discussions. We have been pretty deliberate about not doing this, but that has also necessarily required being consciously careful. Instead, we should add validation that rejects any system names with colons.

The most straightforward thing to do here is probably to throw an exception in `db.addExternalIds()` if the system name has a colon here:

https://github.com/usdigitalresponse/appointment-availability-infra/blob/c7a66c5bfd092cf414432f7bc7dab0cec79a49c1/server/src/db.ts#L116-L140

And we should have at least one test for this, too.

**Comment by channiemills** [comment]
Hi @Mr0grog - question on this one. The `externalIds` are an array object. If some have colons but others do not, would we want to add the valid `externalIds` or throw the exception and not add any?

**Comment by Mr0grog** [comment]
I think throwing and not adding any is a better approach here. It keeps us on the happy path for dealing with errors (transactions will automatically roll back, errors will be automatically formatted in HTTP responses, Sentry will capture it, etc.) without any added complexity, and keeps it easy to reason about results (if you send bad data, everything is rejecting and you don't have to worry about which parts succeeded or failed).

**Comment by channiemills** [comment]
Sounds good, thanks for confirming @Mr0grog
