### ISSUE TITLE
Addresses are not always parsed correctly

### ISSUE THREAD

**Issue by janovergoor** [usdigitalresponse/univaf#235]
Like: `449c8c09-5824-40ab-8882-5b6639cf6815` has `2440 Hamburg Turnpike Wayne, NJ 07470`. This should be parsed into address, city, state, and zip, but the city is hiding because there is a comma missing. We can still parse out the state and zip though, or we can be gregarious and take the last term as the city in those cases.

I'm pretty sure there were cases that would have been easy to parse, like `2440 Hamburg Turnpike, Wayne, NJ 07470`, but I can't seem to find any right now.

In my code, I have something like this for the NY cases:

```
if ', NJ' in address and zip is None:
    zip = address[-5:]
    city = address.split(', ')[1]
    address = address.split(', ')[0]
```

but looking at the case above it should be more failsafe..

**Comment by Mr0grog** [comment]
We definitely made a lot of address parsing improvements over time, and hopefully most of these were addressed, even though it looks like this issue got lost in the shuffle. Closing this since we are ramping down the service.
