### ISSUE TITLE
Set up dependabot

### ISSUE THREAD

**Issue by Mr0grog** [usdigitalresponse/univaf#256]
We should do a better job updating our dependencies. [Dependabot can help](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates). We need special configuration since we have multiple separate packages in this repo.

**Comment by astonm** [comment]
@Mr0grog now that we have @snyk-bot running, do you think we can close this ticket?

**Comment by Mr0grog** [comment]
Yeah, I’ll close this. I think I’m a little underwhelmed with Snyk’s PRs (this is the first time I’ve actually used it; was a little surprised when it suddenly started making PRs after I made the repo public), but I really appreciate that it can find issues in Terraform and Docker files.
