### ISSUE TITLE
Public IPs are currently assigned to each ECS task

### ISSUE THREAD

**Issue by jaronoff97** [usdigitalresponse/univaf#363]
Right now public IP addresses are assigned to each ECS task. We want to verify if this is a security risk or a necessity for the project. In the event that it is not a necessity, we should disable it.

**Comment by jaronoff97** [comment]
Ran a port scan on all of the public ips associated with the Fargate tasks, no results. I verified that the ENI these ips are associated with is only on the private VPC. 

Now if we need them is a different question:

> For Auto-assign Public IP, choose whether to have your tasks receive a public IP address. For tasks on Fargate, in order for the task to pull the container image it must either use a public subnet and be assigned a public IP address or a private subnet that has a route to the internet or a NAT gateway that can route requests to the internet.

Given we can't access it already by the public addresses, I'm not sure we need the public-ip. It sounds that's confirmed by this description too.

**Comment by Mr0grog** [comment]
That makes sense, but what’s the right way to test that without potentially breaking the system?

Can we do it just for scheduled tasks (i.e. the loaders) but not the API service and see if they are able to pull images? That way, the worst impact is that we miss a few rounds of loader updates, but the API service never goes down. Or does it have to be cluster-wide?

**Comment by jaronoff97** [comment]
I just checked again here, and the comment above about why you need this for fargate applies to us for the scheduled tasks. When disabling the feature for auto-assign public IP, the schedule task is unable to start due to `Stopped reason ResourceInitializationError: unable to pull secrets or registry auth: pull command failed: : signal: killed`. Given we can't even connect to the public IPs assigned, it's okay for us to keep this flag set to enabled.

**Comment by Mr0grog** [comment]
Thanks for digging into this!
