### ISSUE TITLE
Make docker image tags immutable in AWS

### ISSUE THREAD

**Issue by jaronoff97** [usdigitalresponse/univaf#364]
Right now our docker image tags are mutable. This will ensure no one can overwrite an existing image for a commit.

**Comment by Mr0grog** [comment]
The one exception to this should be the `latest`. Or we should just get rid of that tag — we don't use it to deploy the API server, but I think we might use it to deploy the loaders (so we'll need to update how they get deployed), which I forgot about in the infrared review.
