### ISSUE TITLE
Be more cautious with VTS concordances

### ISSUE THREAD

**Issue by Mr0grog** [usdigitalresponse/univaf#433]
I don’t know if we’ll wind up expanding and re-running the `vtsGeo` (Vaccinate the States) source again, but we need to fix it to be more careful if we do. I spent a stupid amount of time over the last few days fixing incorrect location `external_id` records that are fouling up our `remove-duplicate-locations` script (situations where two locations that are definitely different would have the same external IDs), and I finally tracked the cause down to the VTS import.

Take, for example, this one:

```js
{
  "name": "Rite Aid #RA101859",
  "state": "MD",
  "location_type": "Unknown",
  "phone_number": "410-766-5220",
  "full_address": "7501 RITCHIE HIGHWAY\nGLEN BURNIE, MD 21061",
  "city": "GLEN BURNIE",
  "county": "Anne Arundel",
  "zip_code": "21061",
  "concordances": [
    "vaccinefinder_org:b5ffb9c3-aa0c-4b8d-951a-50086bc0faa7",
    "rite_aid:101859",
    "vaccinespotter_org:7351259",
    "placekey:223-222@63r-b8x-fpv",
    "placekey:226-222@63r-b8v-p9z",
    "_tag_provider:rite_aid",
    "vaccinespotter_org:141545274",
    "_tag_provider:health_mart",
    "health_mart:8356",
    "getmyvax_org:e89757ac-70f6-4434-9f83-46dde3a2ad22"
  ]
}
```

There is in fact a Rite Aid there. But the Health Mart (`health_mart:8356`) is an entirely different place down the road, at 7571 Ritchie Highway. We *had* two separate records for these. After the VTS import, we still have two records, but the name and address and geographic position of the Health Mart have been overwritten with the Rite Aid’s data. There are more like this.

The key thing here is that the location has two different `vaccinespotter_org` IDs. (I think there are also some where it’s `vaccinefinder_org` and/or `vaccinefinder` that have multiple.) Sometimes having more than one is correct — mistakes *have* been made — but that’s pretty rare. The `vtsGeo` source should log a warning but otherwise skip over these.

**Comment by Mr0grog** [comment]
High priority to either fix this or do something that prevents that loader from running. It doesn’t run on any regular schedule (it was a one-off), but I want to make sure we don’t run it accidentally and re-introduce all these errors.

**Comment by astonm** [comment]
Oof, sorry for the trouble, and good that you were able to track down the source of the issues.

**Comment by Mr0grog** [comment]
No worries, I certainly didn't realize the issue when I reviewed! It might be that they did this correctly more often than they did incorrectly, too, so it's not a total mess. :)

**Comment by Mr0grog** [comment]
De-prioritizing since I made sure we can't accidentally run the loader in #434.

**Comment by Mr0grog** [comment]
At this point, a lot of the VtS data is pretty stale, and I don’t think we’re going to *use* this loader in production again, so I’m just going to close this as *wontfix* so we don’t spend unnecessary effort on it.
